export const CATEGORIES_ACTION_TYPES = {
  SET_CATEGORIES: "categories/SET_CATEGORIES",
  FETCH_REQUEST_START: "category/FETCH_CATEGORIES_START",
  FETCH_REQUEST_SUCCESS: "category/FETCH_CATEGORIES_SUCCESS",
  FETCH_REQUEST_FAILED: "category/FETCH_CATEGORIES_FAILED",
};
